# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#`hint: import … as`
import numpy as np


In [4]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`

null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange
arange_vector= np.arange(10,50)
arange_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
reshape_vector=np.arange(0,9).reshape(3,3)
reshape_vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`

non_zero = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(non_zero)[0]

print(indices)

[0 1 4]


In [19]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
identity_three= np.eye(3,3)

identity_three

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`

random_three=np.random.random((3,3,3)) #1. üc blok sayisi, 2. üc her blogun kalinligi, 3. üc de üc sütun
random_three

array([[[0.09485761, 0.59124504, 0.30335126],
        [0.2868663 , 0.41332028, 0.61793715],
        [0.30981576, 0.57554531, 0.86789465]],

       [[0.67864044, 0.97615579, 0.52661403],
        [0.24811607, 0.86329608, 0.54781829],
        [0.79449616, 0.75076007, 0.2464699 ]],

       [[0.33593216, 0.16085913, 0.9434356 ],
        [0.31092634, 0.75446194, 0.42507717],
        [0.80186244, 0.59488934, 0.13071723]]])

In [38]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`

random_ten= np.random.random((10,10))

print(f'Minimum value: {random_ten.min()}.')
print(f'Maximum value: {random_ten.max()}.')

Minimum value: 0.04379985766090888.
Maximum value: 0.9847453826947185.


In [41]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`

random_thirty= np.random.random((30))
print(f'Mean value of random_thirty is {random_thirty.mean()}.')

Mean value of random_thirty is 0.5884857852426714.


In [42]:
random_thirty

array([0.84494227, 0.70343164, 0.08204401, 0.26334729, 0.89335096,
       0.89734112, 0.91695197, 0.99759171, 0.48604934, 0.55023511,
       0.707407  , 0.07669126, 0.09824092, 0.56759673, 0.95573246,
       0.85958731, 0.99366207, 0.22977071, 0.20631615, 0.66151554,
       0.4498114 , 0.69076443, 0.37373507, 0.08192645, 0.58094913,
       0.70871983, 0.28424294, 0.76786443, 0.92571439, 0.79903992])

In [57]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`

diagonal = np.diag(np.array([1,2,3,4,0]))
diagonal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0]])

In [62]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`

random_norm= np.random.random((5,5))
(random_norm-random_norm.mean())/random_norm.std()

array([[ 0.80881187,  1.21743871, -0.0630356 , -1.06630237,  0.85197417],
       [ 0.86877287, -0.02748049, -1.2685134 ,  1.22705461,  0.88901237],
       [-0.31796064,  0.20079035,  1.03512085,  1.35777222, -0.87100051],
       [-0.06725169, -1.34368148, -1.75131303,  0.62214056,  1.26006662],
       [ 0.38688163, -0.99174327, -1.82627587, -0.03612896, -1.0951495 ]])

In [74]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`

common_1=np.arange(0,10).reshape(2,5)
common_2=np.arange(6,16).reshape(5,2)
common_3=np.intersect1d(common_1, common_2)

common_3

array([6, 7, 8, 9])

In [73]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`

random_vector= np.random.random((10))
random_vector.sort()

random_vector

array([0.00888075, 0.0614132 , 0.15581665, 0.17685861, 0.22172957,
       0.47763698, 0.48849312, 0.50748151, 0.6306971 , 0.80273004])

In [82]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`

random_max= np.random.random((10))
random_max

array([0.29972027, 0.1422432 , 0.09536661, 0.34836798, 0.07968392,
       0.61950323, 0.87139218, 0.90244832, 0.93920752, 0.82395994])

In [83]:
random_max[random_max.argmax()]=0
random_max

array([0.29972027, 0.1422432 , 0.09536661, 0.34836798, 0.07968392,
       0.61950323, 0.87139218, 0.90244832, 0.        , 0.82395994])

In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`

reshape_vector=np.arange(0,9).reshape(3,3)

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [93]:
reshape_vector=np.arange(0,9).reshape(3,3)
reshape_vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
reshape_vector.mean(axis=1, keepdims=True)

array([[1.],
       [4.],
       [7.]])

In [3]:
largest= np.arange(0,9).reshape(3,3)

In [4]:
largest

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.random.shuffle(largest)

In [6]:
largest

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [114]:
largest.sort()

In [115]:
largest

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [116]:
np.argsort(largest)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])